---
- name: install mariadb server
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
- name: Install MYSQL
  yum:
    name: mariadb-server #debian: mysql-server
    state: present
- name: Install the Python MySQL Support Libraries
  yum: pkg=MySQL-python state=latest
- name: start mysql server and enable it on reboot
  service: name=mariadb state=started enabled=true
